---
# This playbook contains common plays that will be run on all nodes.

- name: Install chrony
  yum:
    name: chrony
    state: present
  tags: chrony

- name: Configure chrony file
  template:
    src: chrony.conf.j2 
    dest: /etc/chrony.conf
  tags: chrony
  notify: restart chronyd

- name: ReStart the chrony service
  service:
    name: chronyd
    state: restarted
    enabled: yes
  tags: chrony

