# Title: clusterpeer.yml

---
- hosts: localhost
  collections:
    - netapp.ontap
    - amazon.aws
  gather_facts: false
  name: test Playbook to create a cluster peering

  tasks:
    - name: Create cluster peer
      debug: msg="{{ lookup('amazon.aws.aws_secret', 'FSx.password', nested=true) }}"
