---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
   - mariadb105-server
   - mariadb105-devel
   - python3-libsemanage
   - python3-libselinux

- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - restart mariadb

- name: Start Mysql Service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: mysql client install
  ansible.builtin.shell: |
    mysql -e "CREATE DATABASE "foodb" CHARACTER SET utf8mb4"
    mysql -e "CREATE USER 'foouser'@'localhost' IDENTIFIED BY 'abc'"
    mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'foouser'@'localhost'"

- name: ReStart Mysql Service
  service:
    name: mariadb
    state: restarted
    enabled: yes
