- name: apache2
  apt:
     name: apache2
     state: latest

- name: echo
  command: echo foo

- name: template file1 create
  template: src=apache2_conf dest={{ apache2_conf }}
  notify:
   - restart httpd
  tags: create file

